### ISSUE TITLE
Issues with SDK

### ISSUE THREAD

**Issue by whydna** [browserless/browserless#4189]
**Describe the bug**
Running into a few issues trying to get the hello world example for the SDK working:

1. The helloworld route uses `logger.verbose()` so `npm run build` fails.
2. Looks like this was updated to `logger.trace()` so after fixing that, it seems to build.
3. `npm run start`, `npm run dev` all fail complaining of missing chromium binary:
```
Unhandled Rejection at: Promise {
  <rejected> Error: Couldn't load route "/content,/chromium/content" due to missing browser binary for "ChromiumCDP"
```
4. `npm run docker`  fails as well:
```
 npm run docker

> browsers@1.0.0 docker
> DEBUG=browserless* browserless docker

  browserless.io:sdk:log Cleaning build directory +0ms
  browserless.io:sdk:log Compiling TypeScript +2ms
  browserless.io:sdk:log Building custom routes +1s
  browserless.io:sdk:log Building route runtime schema validation +1ms
  browserless.io:sdk:log Generating OpenAPI JSON file +468ms
  browserless.io:sdk:log All built assets complete +41ms
  browserless.io:sdk:log Generating Dockerfile at "/build/Dockerfile" +0ms
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EISDIR: illegal operation on a directory, open '/build'] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/build'
}
```

**To Reproduce**

1. `npx @browserless.io/browserless create`
2. `npm run build`
3. `npm run start`
4. `npm run dev`
5. `npm run docker`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joelgriffith** [comment]
Nice find, thanks for raising this

**Comment by joelgriffith** [comment]
Should be fixed in https://github.com/browserless/browserless/pull/4214

**Comment by openam** [comment]
@joelgriffith I think #4214 only fixes some of the issues, i.e. the change to the logger, and some of the docker build.

I'm still seeing the following error for `npm start` and `npm run dev`

```
Error: Couldn't load route "/content,/chromium/content" due to missing browser binary for "ChromiumCDP"
      at file:///Users/michael/Developer/browserless/user-data-dir-2-16-0/node_modules/@browserless.io/browserless/build/browserless.js:202:23
      at Array.forEach (<anonymous>)
      at Browserless.start (file:///Users/michael/Developer/browserless/user-data-dir-2-16-0/node_modules/@browserless.io/browserless/build/browserless.js:197:19)
```

Next issue with `npm run docker`
```
npm run docker

> docker
> DEBUG=browserless* browserless docker

  browserless.io:sdk:log Cleaning build directory +0ms
  browserless.io:sdk:log Compiling TypeScript +2ms
  browserless.io:sdk:log Building custom routes +1s
  browserless.io:sdk:log Building route runtime schema validation +0ms
  browserless.io:sdk:log Generating OpenAPI JSON file +440ms
  browserless.io:sdk:log All built assets complete +35ms
  browserless.io:sdk:log Generating Dockerfile at "/Users/michael/Developer/browserless/user-data-dir-2-16-0/build/Dockerfile" +0ms
  browserless.io:prompt Which docker image do you want to use (defaults to: ghcr.io/browserless/multi)? +0ms
  > 
  browserless.io:prompt Do you want to push the image or load it locally (defaults to load)? +0ms
  > 
  browserless.io:prompt What do you want to name the resulting image (eg, my-browserless:latest)? +0ms
  > my-browserless:latest
  browserless.io:prompt Which platform do you want to build for (defaults to linux/amd64)? +0ms
  > 
  browserless.io:prompt Will execute "docker buildx build --build-arg FROM=ghcr.io/browserless/multi --platform linux/amd64 --load -f ./build/Dockerfile -t my-browserless:latest ." Proceed (y/n)? +0ms
  > y
  browserless.io:sdk:log Starting docker build +22s
file:///Users/michael/Developer/browserless/user-data-dir-2-16-0/node_modules/@browserless.io/browserless/bin/browserless.js:329
    await buildDockerImage(cmd, projectDir);
    ^

ReferenceError: buildDockerImage is not defined
    at buildDocker (file:///Users/michael/Developer/browserless/user-data-dir-2-16-0/node_modules/@browserless.io/browserless/bin/browserless.js:329:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
```

As the error states `buildDockerImage` function does not exist, when trying this command `await buildDockerImage(cmd, projectDir);`. Is that supposed to be a function that spawns a child? I'd assume `projectDir` is needed for the cwd of a spawned process.

**Comment by openam** [comment]
@joelgriffith I think #4214 only fixes some of the issues, i.e. the change to the logger, and some of the docker build.

I'm still seeing the following error for `npm start` and `npm run dev`

```
Error: Couldn't load route "/content,/chromium/content" due to missing browser binary for "ChromiumCDP"
      at file:///Users/<username>/Developer/browserless-sdk-project/node_modules/@browserless.io/browserless/build/browserless.js:202:23
      at Array.forEach (<anonymous>)
      at Browserless.start (file:///Users/<username>/Developer/browserless-sdk-project/node_modules/@browserless.io/browserless/build/browserless.js:197:19)
```

Next issue with `npm run docker`
```
npm run docker

> docker
> DEBUG=browserless* browserless docker

  browserless.io:sdk:log Cleaning build directory +0ms
  browserless.io:sdk:log Compiling TypeScript +2ms
  browserless.io:sdk:log Building custom routes +1s
  browserless.io:sdk:log Building route runtime schema validation +0ms
  browserless.io:sdk:log Generating OpenAPI JSON file +440ms
  browserless.io:sdk:log All built assets complete +35ms
  browserless.io:sdk:log Generating Dockerfile at "/Users/<username>/Developer/browserless-sdk-project/build/Dockerfile" +0ms
  browserless.io:prompt Which docker image do you want to use (defaults to: ghcr.io/browserless/multi)? +0ms
  > 
  browserless.io:prompt Do you want to push the image or load it locally (defaults to load)? +0ms
  > 
  browserless.io:prompt What do you want to name the resulting image (eg, my-browserless:latest)? +0ms
  > my-browserless:latest
  browserless.io:prompt Which platform do you want to build for (defaults to linux/amd64)? +0ms
  > 
  browserless.io:prompt Will execute "docker buildx build --build-arg FROM=ghcr.io/browserless/multi --platform linux/amd64 --load -f ./build/Dockerfile -t my-browserless:latest ." Proceed (y/n)? +0ms
  > y
  browserless.io:sdk:log Starting docker build +22s
file:///Users/<username>/Developer/browserless-sdk-project/node_modules/@browserless.io/browserless/bin/browserless.js:329
    await buildDockerImage(cmd, projectDir);
    ^

ReferenceError: buildDockerImage is not defined
    at buildDocker (file:///Users/<username>/Developer/browserless-sdk-project/node_modules/@browserless.io/browserless/bin/browserless.js:329:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
```

As the error states `buildDockerImage` function does not exist, when trying this command `await buildDockerImage(cmd, projectDir);`. Is that supposed to be a function that spawns a child? I'd assume `projectDir` is needed for the cwd of a spawned process.

**Comment by joelgriffith** [comment]
Thanks for raising -- this [PR](https://github.com/browserless/browserless/pull/4218) addresses that as well. With it I was able to create, build, and make a docker image
