### ISSUE TITLE
Error: Couldn't load route "/chrome/content?(/)" due to missing browser binary for "ChromeCDP"

### ISSUE THREAD

**Issue by themagicpanda** [browserless/browserless#4327]
**Describe the bug**
When trying to start Browserless I get an error: Error: Couldn't load route "/chrome/content?(/)" due to missing browser binary for "ChromeCDP"

**To Reproduce**

Install Browserless 2.21.0
Attempt to run browserless
Review error

**Expected behavior**
I would like Browserless to start without error.

**Additional context**
Server is a fresh install of Debian12.

**Comment by joelgriffith** [comment]
Are you running this via docker or bare with nodejs?

**Comment by themagicpanda** [comment]
Hi,

At the moment, it’s a new install on a bare metal Debian server.

**Comment by enviousjag** [comment]
also facing this issue when installing via npm run build && npm prune production.

**Comment by joelgriffith** [comment]
You can fix this for now by running: `./node_modules/playwright-core/cli.js install chromium firefox webkit`. We'll work on fixing this in our package.json scripts

**Comment by AnKlaGo** [comment]
Unfortunately not, still the same error message after when trying to start

**Comment by stickpin** [comment]
@AnKlaGo, @enviousjag I've fixed it: https://github.com/tteck/Proxmox/pull/3928

Once merged, should work for you as well. :)

**Comment by xrb936** [comment]
> @AnKlaGo, @enviousjag I've fixed it: [tteck/Proxmox#3928](https://github.com/tteck/Proxmox/pull/3928)
> 
> Once merged, should work for you as well. :)

It still happens. I am using `npm run build && npm prune` to install.

**Comment by justinkook** [comment]
Still running into this issue as well.

**Comment by ray-magini** [comment]
@justinkook @xrb936 I had the same problem. After following the new procedure from @stickpin it worked for me: https://github.com/tteck/Proxmox/commit/32c24f69a7ea22b9b5854ed9c9203e77ef030deb
